name: CI-humble
on:
  push:
    branches:
      - 'develop'
      - 'humble'
  pull_request:
    branches:
      - 'develop'
      - 'humble'
  workflow_dispatch:
    branches:
      - '*'
jobs:
  industrial_ci:
    name: ROS 2 humble
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: humble
          ROS_REPO: main
