name: CI-humble
on:
  push:
    branches:
      - 'develop'
      - 'humble'
  pull_request:
    branches:
      - 'develop'
      - 'humble'
  workflow_dispatch:
    branches:
      - '*'
jobs:
  ros_humble:
    name: ROS 2 humble
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout LVR2
        uses: actions/checkout@v4
        with:
          submodules: recursive
  
      - name: Compile for ROS2 humble
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: humble
          ROS_REPO: main

      - name: Execute LVR2 Reconstruct
        run: cd $BASEDIR/${PREFIX}target_ws && ./devel/bin/lvr2_reconstruct src/lvr2/dat/scan.pts