name: CI-humble
on:
  push:
    branches:
      - 'develop'
      - 'humble'
  pull_request:
    branches:
      - 'develop'
      - 'humble'
  workflow_dispatch:
    branches:
      - '*'
jobs:
  ros_humble:
    name: ROS 2 humble
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
    env:
      CCACHE_DIR: "${{ github.workspace }}/.ccache" 
    steps:
      - name: Checkout LVR2
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Compile for ROS2 humble
        uses: 'ros-industrial/industrial_ci@master'
        env:
          ROS_DISTRO: humble
          ROS_REPO: main
      - uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-humble-${{github.run_id}}
          restore-keys: |
            ccache-humble-
